### ISSUE TITLE
Sudden glitch causes robot to crash

### ISSUE THREAD

**Issue by laurensvalk** [laurensvalk/segway#10]
Often, the robot will balance just fine for minutes straight. Very constant behavior, with minor motion back and forth.

Then all of a sudden, it starts to sway and falls over, for no apparent reason.

Is anyone else experiencing this?

**Things to look for**
- Potential bug in Segway code
  - Overflow
  - Issue with [deque](https://github.com/laurensvalk/segway/blob/master/ev3/ev3dev/python/segway.py#L163)
  - Math error (/0)
  - Rounding error
  - Sending incorrect duty signal, outside [-100,100]. Or noninteger
- Corrupt / Missing sensor data 
  - Outlier
  - (Persistently) incorrect value
  - Sensor(s) not giving new data
- Timing glitch, loop hanging for too long, causing all kinds of problems:
  - Incorrect signal time integration
  - Incorrect signal derivatives (motor speed)
  - Correlation with Bluetooth/Wifi being active?
  - Some useful info [here](https://github.com/ev3dev/ev3dev/issues/324)

As a start, some data logging code may help.

**Comment by gregcowell** [comment]
I've done some preliminary tests. The following lists the times it took for the EV3  to fall over.

Latest Python code running on Stretch: 40 sec, 3 min, 3 min, 1 min 15 sec, 1 min 45 sec, 1 min 40 sec, 0 sec, 0 sec, 0 sec (did not start balancing again until EV3 powered off and on again)

Latest Python code running on Jessie: 1 min 45 sec, 6 min 55 sec, 14 min

EV3-G: no falls, stopped test after 20 min

Bluetooth/Wifi not active in all tests. 

I'll see if adding some data logging code can shed any light on the problem.

**Comment by gregcowell** [comment]
I have found that the reliability has been increasing as my testing proceeds. Now getting 10 to 15 minutes before the EV3 falls over. Perhaps an anomaly or perhaps due to lower battery voltage ? 

When the EV3 falls over the following exception is raised:
```
Traceback (most recent call last):
  File "/home/robot/ev3dev-lang-python-demo/robots/BALANC3R/ev3dev/control/GyroBalancer.py", line 374, in main
    gyroRateRaw = FastRead(self.gyroSensorValueRaw)
  File "/home/robot/ev3dev-lang-python-demo/robots/BALANC3R/ev3dev/control/GyroBalancer.py", line 47, in FastRead
    return(int(infile.read().decode().strip()))
OSError: [Errno 6] No such device or address
```
So it appears as though the gyro sensor device file can not be accessed. I'll keep investigating.

**Comment by laurensvalk** [comment]
Thanks for sharing your findings! Could you also share how you launched the program? (Brickman, VSCode, terminal, etc.)

In those cases where it fell after balancing for some time, could you report if it was "sudden"? Slowly deteriorating performance possibly means that the tuning values aren't that great. The sudden crashes may have a different origin, however.

> 0 sec, 0 sec, 0 sec (did not start balancing again until EV3 powered off and on again)

Right! I've seen this too, although it appears to be a separate issue. Perhaps I'm not appropriately shutting the program down and something keeps running in the background, thus slowing down the main program.

> So it appears as though the gyro sensor device file can not be accessed. I'll keep investigating.

Do you see this error message just before or after it falls over? Sometimes the physical impact can cause this, when the cables briefly loose contact. In that case, the actual cause may occur prior to this.

**Comment by gregcowell** [comment]
>Could you also share how you launched the program?

Brickman

>could you report if it was "sudden"?

Yep, quite sudden.

>Do you see this error message just before or after it falls over?

After. Brickman sends stderr output to a file which I can look at afterwards. Fortunately the log messages are time stamped.

Here is the full log for a particular crash:
```
2017-10-30 04:11:35,439  INFO: Starting BALANC3R
2017-10-30 04:11:35,781  INFO: Hold robot upright. Press Touch Sensor to start.
2017-10-30 04:11:46,150  INFO: -----------------------------------
2017-10-30 04:11:46,176  INFO: Calibrating...
2017-10-30 04:11:47,480  INFO: GyroOffset: 0.2
2017-10-30 04:11:47,503  INFO: -----------------------------------
2017-10-30 04:11:47,529  INFO: GO!
2017-10-30 04:11:47,551  INFO: -----------------------------------
2017-10-30 04:11:47,573  INFO: Press Touch Sensor to re-start.
2017-10-30 04:11:47,597  INFO: -----------------------------------
2017-10-30 04:22:45,170 ERROR: [Errno 6] No such device or address
Traceback (most recent call last):
  File "/home/robot/ev3dev-lang-python-demo/robots/BALANC3R/ev3dev/control/GyroBalancer.py", line 374, in main
    gyroRateRaw = FastRead(self.gyroSensorValueRaw)
  File "/home/robot/ev3dev-lang-python-demo/robots/BALANC3R/ev3dev/control/GyroBalancer.py", line 47, in FastRead
    return(int(infile.read().decode().strip()))
OSError: [Errno 6] No such device or address
2017-10-30 04:22:45,331  INFO: Exiting BALANC3R
```

Here is the kernel log for the corresponding period:
```
Oct 30 04:11:18 ev3dev kernel: ev3_uart_receive_buf: 56 callbacks suppressed
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:11:18 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:46 ev3dev kernel: tty ttyS0: Reconnected due to: No data since last keep-alive.
Oct 30 04:22:46 ev3dev kernel: ev3_uart_receive_buf: 54 callbacks suppressed
Oct 30 04:22:46 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:46 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:46 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
Oct 30 04:22:47 ev3dev kernel: ttySU0: buffer overrun
```

The crash occurred at 4:22 but there are kernel error messages beginning from the time when the program was started. I am hoping it is a kernel UART buffer size issue rather than the connection being briefly lost when the EV3 falls. I'm not sure though. I will keep investigating.

**Comment by laurensvalk** [comment]
Thanks for the update.

> I am hoping it is a kernel UART buffer size issue rather than the connection being briefly lost when the EV3 falls.

I meant that the cables might briefly disconnect upon hitting the ground. I've not seen it with the gyro yet, but I've seen it happen when the robot falls on one of the motor cable connector clips, thus disconnecting the motor cable.

This shouldn't be the issue, though, if we find what causes it to fall in the first place.

And it looks like you are already onto something :+1:

**Comment by gregcowell** [comment]
Thanks Laurens. Yep, when I said “connection being briefly lost” I was referring to the cable being disconnected briefly.

**Comment by laurensvalk** [comment]
Can you run the following and report the results here or [here](https://github.com/ev3dev/ev3dev/issues/679#issuecomment-340463164)?

```
ev3dev-sysinfo -m
```

**Comment by gregcowell** [comment]
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-09-30
Kernel version:     4.9.49-ev3dev-1.5.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534FB669
BOARD_INFO_TYPE=main
```

**Comment by laurensvalk** [comment]
> I have found that the reliability has been increasing as my testing proceeds. Now getting 10 to 15 minutes before the EV3 falls over. Perhaps an anomaly or perhaps due to lower battery voltage ?

~~I'll add my findings just in case: I just started the program after letting the battery slowly discharge for 2 weeks. So simply not using it for some time.~~

~~Battery is at 7.11. I haven't seen the issue at all yet. (And I haven't done any upgrades since opening this issue.) I'll recharge overnight and try again tomorrow.~~

```
[  131.042093] ev3_uart_receive_buf: 49 callbacks suppressed
[  131.042137] ttyS0: buffer overrun
[  131.043591] ttyS0: buffer overrun
[  131.045758] ttyS0: buffer overrun
[  131.048072] ttyS0: buffer overrun
[  131.048218] ttyS0: buffer overrun
[  131.050674] ttyS0: buffer overrun
[  131.058431] ttyS0: buffer overrun
[  131.059089] ttyS0: buffer overrun
[  131.060649] ttyS0: buffer overrun
[  131.062170] ttyS0: buffer overrun
```
The robot loses balance and falls over. There's no reconnect message; all sensors continue to work afterwards.

When restarting the loop using the Touch Sensor, all continues to work fine. 
```
Image file:         ev3dev-stretch-ev3-generic-2017-10-24
Kernel version:     4.9.49-ev3dev-1.5.1-ev3
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=001653420A17
BOARD_INFO_TYPE=main
```

In my case this was with Bluetooth and the VSCode Extension.

**Comment by gregcowell** [comment]
I've also seen that behaviour. If I can get it to happen again, I'll do some logging to try to see what is happening. I suspect that the sensor read latency increases to a point at which the loop time gets too large.

**Comment by laurensvalk** [comment]
See also the issue linked to in the first post, with [the two diagrams in this post in particular](https://github.com/ev3dev/ev3dev/issues/324#issuecomment-101784141).

**Comment by gregcowell** [comment]
>Sometimes the physical impact can cause this, when the cables briefly loose contact. In that case, the actual cause may occur prior to this.

Yes, confirmed. The exception was being raised due to the connector to the gyro sensor getting loose on impact. The program no longer terminates when the EV3 falls over.

I have recompiled the kernel with a EV3_UART_BUFFER_SIZE of 8192 instead of 1024. The kernel error messages have gone away but the EV3 still falls over. Also, I have not recharged my batteries yet and the time until a fall is quite short again. 

New kernel details:
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2017-09-30
Kernel version:     4.9.58-ev3dev-1.6.0-ev3+
Brickman:           0.10.0
ev3devKit:          0.5.2
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534FB669
BOARD_INFO_TYPE=main
```

**Comment by gregcowell** [comment]
Just did three tests with the modified kernel. No buffer overrun messages were logged. The first two tests only lasted a couple of minutes. The third test lasted 22 minutes which is the longest I've seen. 

Not sure if this is happening but if I do not hold the EV3 perfectly still during the calibration/gyro offset calculation phase, am I right in assuming that this will affect the results significantly ?

**Comment by gregcowell** [comment]
>Not sure if this is happening but if I do not hold the EV3 perfectly still during the calibration/gyro offset calculation phase, am I right in assuming that this will affect the results significantly ?

I've done more testing while being very careful with positioning the EV3 and holding it still during calibration. It didn't make any difference though - still falling. 

Kernel modification has made the buffer overrun errors cease but hasn't solved the problem. Perhaps the buffer overruns are unrelated or I am just masking the problem by increasing the UART buffer size.

**Comment by laurensvalk** [comment]
> Not sure if this is happening but if I do not hold the EV3 perfectly still during the calibration/gyro offset calculation phase, am I right in assuming that this will affect the results significantly ?

It should only affect the first 10-20 seconds or so, as a calibration routine keeps running as time goes on (see the part of the loop where the offset is being adjusted).

The initial calibration is to get an initial estimate of the offset. If it isn't quite right when you don't hold it very still, you'll see it drive to one direction for some distance and stabilize there. Because of the accumulated motor angle error, it eventually returns to the zero position. 

Either way, it shouldn't affect the long time performance.

> I have recompiled the kernel with a EV3_UART_BUFFER_SIZE of 8192 instead of 1024. The kernel error messages have gone away but the EV3 still falls over. (...) Kernel modification has made the buffer overrun errors cease but hasn't solved the problem. Perhaps the buffer overruns are unrelated or I am just masking the problem by increasing the UART buffer size.

Thanks for trying all this!

**Comment by laurensvalk** [comment]
We can also do some datalogging to see if the delayed sensor data as reported in the first post is still an issue. 

Hopefully I'll soon get a chance to try it out with the HiTechnic sensor, which is an analog sensor and shouldn't be affected by this problem (if the UART sensor really is the problem at all.)

We might also want to do a data logging experiment with the EV3-G software since it has no balancing issues. Perhaps also compare with [ev3dev+lms2012 compat](https://github.com/ev3dev/lms2012-compat).

It would be useful to begin with a data logging experiment separate from the balancing code. 

A good starting point is to place BALANC3R's with its wheels resting on two tabletops with equal height, with the main body passively swinging back and forth in the middle.

I did this about two years ago:

![swing](https://cloud.githubusercontent.com/assets/12326241/7583382/09481520-f895-11e4-8d55-2bd3f897cf41.png)

It would be interesting see what we might get now. And this time also compare with EV3-G.

**Comment by gregcowell** [comment]
Thanks Laurens. I’ll focus on data logging next.

**Comment by gregcowell** [comment]
I've repeated your data logging experiment. Below are the results. Each graph uses the same data set. I've zoomed in to show more detail. My script just samples as quickly as possible. The maximum delay between samples appears to be about 20ms.

![gyro1](https://user-images.githubusercontent.com/22849618/32307866-7332a8ee-bfce-11e7-8fdd-b08aac527f27.png)

![gyro2](https://user-images.githubusercontent.com/22849618/32307925-d6309410-bfce-11e7-8603-81fb86aea154.png)

![gyro3](https://user-images.githubusercontent.com/22849618/32307932-dbb2a860-bfce-11e7-8f82-735c01906dfd.png)

**Comment by laurensvalk** [comment]
Thanks for sharing this, and for sharing your code as well. Here are some tips for future logging sessions:

----

```
        while not touch_sensor.is_pressed:
            sample_time = time.time()
            data[(sample_time - start_time) * 1000.0] = FastRead(gyro_data)
```
I think you can speed this part up quite a bit by using FastRead for the touch sensor as well, or by not using the touch sensor at all (e.g. just looping for 10 seconds). 

Especially the latter should increase the sampling rate by a factor 2 or more, since there are half as many file reads, and the regular read is not as fast.

----

In the second plot, just before 700 ms, do you think this is due to the sensor or could there have been a mechanical disturbance? (e.g. minor touch after letting it go or something underneath the wheel.)

If it were the sensor, I would expect the signal to "catch up" after the glitch as in the previously posted plot, but here it looks like the acceleration was briefly halted mechanically.

--- 

To make the data set start at 0, you can unplug the gyro sensor and plug it back in again prior to starting the script. This resets the sensor internally. (Keep the sensor at rest while plugging it in.)

**Comment by gregcowell** [comment]
>In the second plot, just before 700 ms, do you think this is due to the sensor or could there have been a mechanical disturbance?

I'm guessing it was just a small mechanical disturbance.

**Comment by gregcowell** [comment]
I've updated the code as per your suggestions and the sampling rate is much faster. I'll collect some more data and post the results.

**Comment by gregcowell** [comment]
Results with the fastest possible sampling rate:
![gyro10](https://user-images.githubusercontent.com/22849618/32324816-5907c45a-c018-11e7-81c6-11713fa752cb.png)

![gyro11](https://user-images.githubusercontent.com/22849618/32324817-59408074-c018-11e7-8736-52975e283120.png)

![gyro12](https://user-images.githubusercontent.com/22849618/32324818-5977eb36-c018-11e7-8981-ec3496e68907.png)

The axles turn slightly as the swing direction changes. I wonder if this has any significant effect on the results.

**Comment by laurensvalk** [comment]
Thanks for the update. It looks like we still have those delays. 

Do you see both case (1) and (2) of [this post](https://github.com/ev3dev/ev3dev/issues/324#issuecomment-101784141) in your data?

**Comment by laurensvalk** [comment]
By the way, if you want to save some time on sharing plots and data, consider plotly with Jupyter. Each time you commit, you can just share the link to your notebook in which people can interactively view the plots in their browser. [Example](http://nbviewer.jupyter.org/github/laurensvalk/devbots/blob/b23b8d8352ce1f68c562dc9ba1d0d6b496104b35/jupyter/dynamics-plots.ipynb).

**Comment by gregcowell** [comment]
>Do you see both case (1) and (2) of this post in your data?

Yep, both occur when the sample rate is below 20ms. Given that your segway code uses a loop time of 30ms, is this still a concern ?

>By the way, if you want to save some time on sharing plots and data, consider plotly with Jupyter. 

Thanks, I'll check it out.

**Comment by laurensvalk** [comment]
That's good to know.

It could be a concern, but it's hard to say from this experiment whether
this causes the sudden balance disturbance.

The next step could be to run a similar data log experiment while the
Segway is balancing, and seeing whether the data near the sudden crash is
similar to what we're seeing here.

(Who knows, if it turns out there is no relation at all, the issue might
not be the Gyro sensor)

Your experiment above will help in interpreting future experiments because
those will likely have lower sampling rates.

**Comment by gregcowell** [comment]
Here is my first attempt at logging data while the segway is balancing. You may have suggestions for other data I could collect. I've just collected loop duration and gyro readings for now. You can see the fall at the end. There were two notable clusters of longer loop times. The fall occurs during the second and most severe one.

![loop1](https://user-images.githubusercontent.com/22849618/32357370-d09c1db2-c087-11e7-8143-67f4da04d6ac.png)

![data1](https://user-images.githubusercontent.com/22849618/32357579-cfc89774-c089-11e7-8de8-6e5df8707056.png)

Fall / second cluster of long loop times:
![loop4](https://user-images.githubusercontent.com/22849618/32357478-d55bc874-c088-11e7-9be0-e2d2b6d5d320.png)

![data4](https://user-images.githubusercontent.com/22849618/32357483-dc595402-c088-11e7-9a73-2680d799b4c6.png)

**Comment by laurensvalk** [comment]
Thanks again for doing these experiments and repeating the loop time experiment. Very insightful. 

The first big peak is also a bit worrying at > 200 ms, but it's good to see it can recover if there aren't too many of those sequentially.

This data suggests that imbalance is caused by the longer loop times indeed. Longer loop times begin at 4.378e5, and immediately after the robot starts to fall over. (Steady nonzero gyro rate.)

This may still correlate with the UART sensor(s), WiFi, Bluetooth, by the way, since they cause extra kernel activity.

There may be ways to deal with these delays in the user program. It might be possible to adjust the integrated and differentiated signals retrospectively, but that's not guaranteed to work. I'll have to think about that.

----

>  You may have suggestions for other data I could collect

Perhaps when presenting multiple plots to derive conclusions from the data, plot them at the same time scale and horizontal alignment. It took me a while to realize that the vertical bars in the last plot span 500 ms, not 1000 as above.

**Comment by gregcowell** [comment]
>This may still correlate with the UART sensor(s), WiFi, Bluetooth, by the way, since they cause extra kernel activity.

I agree. I have not been using Bluetooth or WiFi though.

>Perhaps when presenting multiple plots to derive conclusions from the data, plot them at the same time scale and horizontal alignment.

I've taken a quick look at plotly. Unfortunately the free tier upload limit is too small for my data set. It looks like a fantastic tool though. Here are the graphs of the fall in proper alignment and with a more sensible scale:

![loopandgyro1](https://user-images.githubusercontent.com/22849618/32398415-e8085a3e-c13a-11e7-9c0f-c7326725cddb.png)

Here is an earlier cluster of long loop times where no fall occurred. The loop times are smaller though. It seems like a fall occurs when there is a cluster of long loop times that are 50ms or above.

![loopandgyro2](https://user-images.githubusercontent.com/22849618/32398871-a303a396-c13d-11e7-9a3e-b79ed6c9c5ff.png)

I'm very curious as to why we don't see this problem with EV3-G.  

I am thinking my next steps will be:

1. Logging the same data for the EV3-G version if possible.
2. Researching how the Linux kernel does process scheduling (I realise that this has already been looked at but it is something I'm interested in knowing more about).

**Comment by gregcowell** [comment]
I set the nice level on the python script to -19. I did not see any long loop times but interestingly the robot still fell over. 

![loopandgyro3](https://user-images.githubusercontent.com/22849618/32401907-d3137af8-c164-11e7-9d0b-fc429eb59858.png)

**Comment by laurensvalk** [comment]
> I've taken a quick look at plotly. Unfortunately the free tier upload limit is too small for my data set.

That's their online service, useful to publish e.g. corporate data. The "offline" version is free; no online account required. See [example](http://nbviewer.jupyter.org/github/laurensvalk/devbots/blob/b23b8d8352ce1f68c562dc9ba1d0d6b496104b35/jupyter/dynamics-plots.ipynb) made using this code:

```
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
from IPython.display import display, HTML

x = list(range(0,10))
y = [c*c for c in x]
iplot([{"x": x, "y": y}])
```
They become shareable once you push them to Github. I recently tried 1MB of raw data without issues.

**Comment by laurensvalk** [comment]
> Here is an earlier cluster of long loop times where no fall occurred. The loop times are smaller though. It seems like a fall occurs when there is a cluster of long loop times that are 50ms or above.

Noted. 

> I set the nice level on the python script to -19. I did not see any long loop times but interestingly the robot still fell over.

Very interesting. Just for completeness, can you share the command to achieve the -19 niceness?

---

EV3-G would be useful indeed. However, I'm beginning to wonder what to compare exactly, since the gyro rate and/or loop timing might not be the main issues.

Thanks for sharing all the insights. This is fun :)

**Comment by gregcowell** [comment]
>That's their online service, useful to publish e.g. corporate data. The "offline" version is free; no online account required. 

Sounds good. I'll take another look.

>Very interesting. Just for completeness, can you share the command to achieve the -19 niceness?

First you need to add the following line to /etc/security/limits.conf:
```
robot		-	nice		-20
```
Next, you need to restart your ssh session (log out and log in again) so that the new setting is in effect.

This is the command:
```
nice -n -19 ./balanc3r.py
```
There is also a command called "chrt" which is for setting the real-time attributes of a process. However I didn't try this as the delay issue seems to have been resolved by using nice. I should probably run some more tests to make certain of this as the EV3 fell over relatively early in all my tests using nice so far.

I imagine it would be possible to put the command inside a script so that it can be run from Brickman. This may require using setuid on the script to make it run as the robot user. Probably not necessary though because Brickman runs as root.

>EV3-G would be useful indeed. However, I'm beginning to wonder what to compare exactly, since the gyro rate and/or loop timing might not be the main issues.

If additional testing shows the same results, I'll start looking for other potential causes.

>Thanks for sharing all the insights. This is fun :)

You're welcome. Thanks for creating Segway. It certainly is fun!

**Comment by gregcowell** [comment]
I haven't been able to get Brickman to use nice as yet. However the command below will allow the script to be run via an ssh session over a USB cable. It will continue running when the USB cable is disconnected.
```
nohup nice -n -19 ./balanc3r.py < /dev/null  > balanc3r.log 2>&1 &
```
Example of how to terminate the program:
```
$ ps -ef | grep balanc3r
robot     1895   614 36 00:46 pts/0    00:01:36 python3 ./balanc3r.py
robot     1992   614  0 00:51 pts/0    00:00:00 grep balanc3r
$ kill -9 1895
```
I have run the tests several more times. The loop times are all below 33ms. However the EV3 falls after 30-40s.

**Comment by laurensvalk** [comment]
Does it still fall over all of a sudden or does balance slowly deteriorate over those 30-40s?

**Comment by gregcowell** [comment]
Still all of a sudden. It seems like the EV3 is moving more frequently during those 40s but it does not get progressively worse. The graphs don’t appear to indicate any deterioration until the fall. I’ll keep testing because my initial test results improved over time and I thought that might be related to voltage dropping.

**Comment by laurensvalk** [comment]
I also wrote some datalogging and plot code. Some output is [here](http://nbviewer.jupyter.org/github/laurensvalk/segway/blob/05b986989ac58e6b4720adc5b687e422b5ad3012/ev3/ev3dev/datalog/datalog.ipynb)

I am now anxiously waiting for the bug to actually occur... :smile:

**Comment by gregcowell** [comment]
My most recent data is now in a Jupyter Notebook: [here](http://nbviewer.jupyter.org/github/gregcowell/ev3-experiments/blob/master/datalog/ev3-graphs.ipynb)

I can see some suggestion that the gyro sensor reading did not update for 4 samples starting at the 42.85 second mark.

**Comment by laurensvalk** [comment]
@BertLindeman has created some [video evidence](https://www.youtube.com/watch?v=AFMb7cS8QOs)!

Consider the test cases without WiFi (which is a different disturbing factor, to be resolved at another time).

There are a few sudden crashes. Some are more subtle than others, triggering a slow swing rather than an immediate crash, but still seemingly out of the blue.

Note that he uses the HiTechnic sensor (which is analog), which might rule out some of our UART suspicions...

**Comment by laurensvalk** [comment]
@BertLindeman if you like, see if you still get the same problem if you disconnect the IR Sensor (and comment out any part of the code that uses it). That would rule out any UART traffic problem. 

Don't worry about a new video. Maybe you can pinpoint to segments of your current video that show similar behavior.

**Comment by BertLindeman** [comment]
Will do, but it may be a day or two . . .

**Comment by BertLindeman** [comment]
OK, WIFI OFF / hard floor / disconnected IR-sensor.
Ah rats, had permissions on the datalog wrong :-(, redo.

Dropping looks like the drop at ~1:36 in the movie but to me that looks like the drop at the end of the movie.

Is it usefull to drop the datalog of the last fall here?
Let's try upload; Nope 'filetype not supported', neither a zip:
```
 Something went really wrong, and we can’t process that file.
```
Tried 3 times in FireFox.... 
Retrying upload in Chrome . .  Same problem

OK, datalog via[Ddropbox]{https://www.dropbox.com/s/70y17hbwe4cc478/datalog.ipynb?dl=0}


Not sure: should the eprint output be seen at the EV3 screen if running from the filebrowser?

**Comment by laurensvalk** [comment]
Since you are using Github, it could be easiest to upload your .ipynb there. After you do, you can share the link to it. For example, mine is [here](https://github.com/laurensvalk/segway/tree/master/ev3/ev3dev/datalog), and if you click on it there's a button on the right to a link that also [includes the plots](http://nbviewer.jupyter.org/github/laurensvalk/segway/blob/05b986989ac58e6b4720adc5b687e422b5ad3012/ev3/ev3dev/datalog/datalog.ipynb).

Otherwise, you can always share the .txt file here.

I'm not sure what you meant about the permission. I believe the datalog.txt is created in the same location as your script file.

**Comment by laurensvalk** [comment]
I wanted to add that at this point we're not sure what to look for exactly. Maybe it's not even in the signals data logged so far, so don't worry too much about sharing all datalog files.

**Comment by laurensvalk** [comment]
That said, are you sure you uploaded the right file?

The data looks the same as mine. Statistics was never my favorite topic but something tells me this is extremely improbable :smile:

It also says "Data from: UTC: 2017-11-05-19:38:21".

**Comment by BertLindeman** [comment]
> The data looks the same as mine. Statistics was never my favorite topic but something tells me this is extremely improbable 😄

Ok Laurens, I will forget for the moment the datalog file(s) and I did have an iffy feeling about the date.
So old file is true.
Will go the github way. Thanks.
> I'm not sure what you meant about the permission. I believe the datalog.txt is created in the same location as your script file.

My fault, did some manipulation under root.
Correct: In the directory where the `segway.py` program is located the `datalog.py` is written.

Q: should the eprint output be seen at the EV3 screen if running from the filebrowser?
Could not find in the code (Only on page 92 of "Python Crash Course" book ) ;-)

**Comment by laurensvalk** [comment]
When running from brickman, I believe they go into an error log file which automatically appears in the same folder.

**Comment by BertLindeman** [comment]
Thank, saw the "myGyroBalancer.py.err.log"
Running from the EV3 screen wondered what the correct moment would be to press the touch-sensor.
No problem.

**Comment by laurensvalk** [comment]
Good point. I'll add a beep command in the next version of the code.

**Comment by gregcowell** [comment]
If you zoom in on this data set [here](http://nbviewer.jupyter.org/github/gregcowell/ev3-experiments/blob/master/BALANC3R/datalog/ev3-graphs.ipynb), you can see a significant series of identical gyro readings just before the fall.

This data was collected with the nice level of the python script set to -19.

**Comment by gregcowell** [comment]
Although setting the nice level of the python script does ensure that the loop times are short, the time until fall is much shorter (usually less than a minute as opposed to the usual 10 minutes). I have also noted duplicate gyro readings seem to occur when doing this. 

This data [here](http://nbviewer.jupyter.org/github/gregcowell/ev3-experiments/blob/master/BALANC3R/datalog/ev3-graphs2.ipynb) is the result when I do not set the nice level of the python script. However I did renice the daemons associated with the UART device files (see below). The EV3 stays upright for about 10 minutes. I do not see any duplicate gyro readings in this data (maybe due to the renice of the ldattach daemons).

```
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
1 S root       310     1  0  60 -20 -   442 -      02:00 ?        00:00:00 /usr/sbin/ldattach 29 /dev/tty_ev3-ports:in2
1 S root       324     1  0  60 -20 -   442 -      02:00 ?        00:00:00 /usr/sbin/ldattach 29 /dev/tty_ev3-ports:in4
```

**Comment by laurensvalk** [comment]
Interesting find! 

I probably won't be able to work on this until next week, but feel free to share the findings as you find them.

**Comment by laurensvalk** [comment]
The VEX IQ version (elsewhere in this repository) appears to exhibit similar behavior [at this point in the video](https://youtu.be/1P7SWxnKF_A?t=35s).

It could be something else or it could be the same. If it's the same issue, the cause may be in the code...

**Comment by gregcowell** [comment]
I've experimented with making the code track actual loop times (for use in the calculations). Unfortunately it didn't help. The EV3 still falls over and the fall seems to be in response to long loop times. However as mentioned earlier, setting the nice level to get rid of the long loop times does not solve the problem. 

>If it's the same issue, the cause may be in the code...

I hope it is the same issue so we can narrow it down to the segway code.

**Comment by pipothy** [comment]
Just a brief note on what I saw as I was experimenting with it... I'm testing another algorithm for its computational load on the system in comparison with other solutions, so I've been checking the uptime computational load during the running of the balancing robot.

What *seemed* to be the case was that when these jerks happen, there's a huge spike in computational load. I have no idea if this is expected, or unusual. But, thought I'd put it out there in case it somehow is a nice clue to help people track this down.

**Comment by laurensvalk** [comment]
Thanks for sharing this. What kind of computational load spike are you seeing, and how are you seeing it?

Do you mean that the python script itself occasionally appears to draw a lot of computation power, or do you mean that the script is affected by computational load allocated elsewhere (kernel, other apps)?

**Comment by pipothy** [comment]
I ran the uptime command which gives the average number of computations waiting to be done over the past minute. 

The robot had the bug happen at 30 seconds into a trial I ran and I ran uptime to see a minute average of 1.60. this is huge compared to the .65 idle or the .9 average while running. Just to check it wasn't due to the start up computational load being high, I paused the controller and ran it again after another 30 seconds. This value was 1.15, which is still higher than the average by a good margin. Furthermore, this will have been brought down by the waiting loop having very little computational expense.

Does that make sense? Sorry, on the move and being a bit brief.

**Comment by pipothy** [comment]
To answer your latter question, I have no idea where it's coming from, simply that it seems to correlate with the bug. Since I'm running this command on the underlying Linux system, it could be from anywhere.

**Comment by pipothy** [comment]
I have since found this evidence to be nothing more than coincidental after attempting to repeat results. So, do ignore me.

**Comment by laurensvalk** [comment]
No problem, thanks again for looking into this!

**Comment by gregcowell** [comment]
Just for completeness, I've tried the following:
```
$ nohup ./remote.py < /dev/null > remote.log 2>&1 &
$ ps -ef | grep remote
robot      874   732 52 01:54 pts/0    00:00:09 python3 ./remote.py
$ chrt -p 874
pid 874's current scheduling policy: SCHED_OTHER
pid 874's current scheduling priority: 0
$ sudo chrt --fifo -p 50 874
$ chrt -p 874
pid 874's current scheduling policy: SCHED_FIFO
pid 874's current scheduling priority: 50
```
It didn't stop the fall.

**Comment by gregcowell** [comment]
I decided to go back and test the reliability of the EV3-G version. The robot movement seems a little smoother (perhaps due to shorter loop times). However in both of my tests the robot did fall. One test lasted 5 minutes and the other lasted 15 minutes.

**Comment by laurensvalk** [comment]
Hmm, that's very interesting, thanks for sharing. I remember having it run for hours (at live demos) with few problems other than people knocking it down occasionally :smile:

I don't recall seeing the sudden destabilization.

**Comment by gregcowell** [comment]
>I don't recall seeing the sudden destabilization.

Yep, my previous testing (although minimal) showed no issues at all. I'll do more testing when I get a chance and make sure its not just loose connectors or something.

**Comment by gregcowell** [comment]
I’ve done some more testing of the EV3-G version. Didn’t have any issues this time.

**Comment by laurensvalk** [comment]
A new version of the code is under way that is more robust to tuning, battery level, and sudden glitches. Glitches may still occur, but they no longer crash the robot.

As I write this, I'm turning the robot off after stably balancing for one hour straight. :smile: 

More later!

**Comment by BertLindeman** [comment]
Thanks @laurensvalk. Have not spend too much time on this, but could not find out why I did not get the HiTechnic gyro starting to stabilize. Even if I keep the robot hanging stable in my fingers of stable lying down, the motors keep spinning like crazy. Will re-copy the new scripts and retry tomorrow.

**Comment by laurensvalk** [comment]
Could have been the mounting location :)

Feel free to play with the scripts for now, but I'll need a little more time to update the repository and make new installation and running instructions.

**Comment by BertLindeman** [comment]
Too good a weather now to sit inside ;-) But *will* play with them. TX.

**Comment by BertLindeman** [comment]
For the moment I give up on the HiTechnic Gyro, EV3 gyro has been ordered ;-) Will arrive  day after tomorrow.
The HT gyro *is* available for testing later off course.

**Comment by gregcowell** [comment]
> A new version of the code is under way that is more robust to tuning, battery level, and sudden glitches. Glitches may still occur, but they no longer crash the robot.

Great news!

I will start preparing a pull request to change the GyroBalancer class in the EV3 Python library as soon as you are satisfied the new code is ready.
