### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by laurensvalk** [laurensvalk/segway#17]
I'm currently working on a new version of the code which is a bit more pythonic. Feel free to give it a try if you're interested.

The whole control loop is now about 10 lines of code. The full code is [here](
https://github.com/laurensvalk/segway/tree/pythonic/ev3/ev3dev/pythonic).

For now only the EV3 gyro is supported. I haven't scaled for battery voltage yet, so the tuning may not work for you right away. But with simpler code, it's hopefully easier to modify on your end.

```
# Main loop
while True:
    # Loop start
    start = time()

    # Body angle
    rate = highpass.filter(gyro.rate)
    angle = integrator.integral(rate)

    # Wheel translation
    average_motor_degrees = (right.position + left.position)/2
    distance = average_motor_degrees * cm_per_degree
    speed = differentiator.derivative(distance)

    # Control signal
    duty = gain_angle*angle + gain_rate*rate + \
        + gain_distance*distance + gain_speed*speed

    # Motor actuation
    left.duty(duty)
    right.duty(duty)

    # Sleep until loop complete
    while time()-start < looptime:
        sleep(0.002)
```

The code uses ev3devlight to interface with the hardware, which is a python3 and micropython compatible library. See [this](https://github.com/laurensvalk/ev3devlight-examples) for installation instructions.

It doesn't have all the ev3dev functionality, but it takes only a few seconds to load. It's also faster for reading sensors and controlling motors.

**Comment by laurensvalk** [comment]
@gregcowell, @pipothy, @BertLindeman

**Comment by pipothy** [comment]
Alas, I don't have access to the robot now. I can try it when I do, but that could be a long time. The code looks lovely!

**Comment by BertLindeman** [comment]
After the install the link fails:
```ln -s /home/robot/.micropython/lib/ev3devlight /home/robot/.local/lib/python3.5/site-packages/ev3devlight``` 
results in:
```ln: failed to create symbolic link '/home/robot/.local/lib/python3.5/site-packages/ev3devlight': No such file or directory```
Assumed I need to create the base directories:
`mkdir -p /home/robot/.local/lib/python3.5/site-packages/`

This helps.

Is there a way to use the HiTechnic Gyro in ev3devlight?

**Comment by laurensvalk** [comment]
> Is there a way to use the HiTechnic Gyro in ev3devlight?

There is now support for analog sensors. Repeat the installation instructions to update.

To use the HiTechnic for now, mount the sensor [like this](http://robotsquare.com/wp-content/uploads/2014/06/BALANC3R_21b-550x575.jpg), and replace:

```
# Configure and calibrate LEGO Gyro
gyro = Gyro('in2', read_rate=True, read_angle=False, calibrate=True)
initial_bias = 0
```
With:
```
# Configure and calibrate HiTechnic Gyro
class HiTechnicGyro(Analog):

    """Interface for HiTechnic Gyro."""
    def __init__(self, port):
        """Initialize as analog device with scaling factor."""
        Analog.__init__(self, port, scaling=-4.8)

    @property
    def rate(self):
        """Return gyro rate."""
        return self.output

gyro = HiTechnicGyro('in2')
calibrator = Calibrator()
for i in range(20):
    calibrator.add_sample(gyro.rate)
    sleep(0.02)
initial_bias = calibrator.average
```
In the future I might add the HiTechnicGyro class to ev3devlight. For now I intended to support just LEGO sensors.

**Comment by laurensvalk** [comment]
> After the install the link fails:

Thanks. I recommend to use micropython, though. Running a program takes just seconds.

**Comment by laurensvalk** [comment]
I should also add that this is quite experimental so far, and just intended for those who like to code segway robots :smile:

**Comment by BertLindeman** [comment]
> In the future I might add the HiTechnicGyro class to ev3devlight. For now I intended to support just LEGO sensors.

If there is a workarond - fine by me. Will try possibly today.

> Thanks. I recommend to use micropython, though. Running a program takes just seconds.

Will even look at micropython (so we get all the speed we can get out of the little baby) and by your latest comment, I am well at my place here :-)

> I should also add that this is quite experimental so far, and just intended for those who like to code segway robots 😄

Thanks Laurens,

**Comment by laurensvalk** [comment]
All you'd need to do is:
```
 ./segway.py
```
or run it from vscode. Because of the comment at the top:

```
#!/usr/bin/env micropython
```
micropython is automatically used in both cases.

**Comment by laurensvalk** [comment]
@antonvh.

**Comment by BertLindeman** [comment]
Got the EV3-gyro sensor and tried your current code including the remote steering.

First testing on soft-floor (easier for the bot to survive a hard drop).
Few minutes and jerky movements (Dutch: schokkerig).
Maybe I still have too many services running.

Stopped WIFI and these services: 
nmbd.service, smbd.service, bluetooth.service, ev3-bluetooth.service, avahi-daemon.service
cron.service atd.service ntp.service bluetooth.service

Ran on hard floor (Vynyl) for about 15 minutes. 
Less jerky, looking stable, sometimes recovering a bit jerky but mostly stable. When I was not looking it dropped. the  ev3devlight/segway.py.err.log log contains:
```
Traceback (most recent call last):
  File "/home/robot/ev3devlight/segway.py", line 77, in <module>
  File "/home/robot/.micropython/lib/ev3devlight/sensors.py", line 117, in rate
  File "/home/robot/.micropython/lib/ev3devlight/fileio.py", line 17, in read_int
OSError: 6
```
Maybe this error occurs *after* the drop.

After dinner will look at services still running and try again.
Was tempted  to stop brickman.service but that makes running the test rather difficult ;-)

**Comment by laurensvalk** [comment]
Thanks for trying it out.

It shouldn't be necessary to stop any services as the program has ample
idle time. My Bluetooth was on all the time with no issues.

It's meant to run on a hard floor. If you're worried about damage, you
could also consider mounting some LEGO tyres on either side of the robot.

The file io error may have been caused by a cable briefly disconnecting
during the fall impact.

I'll do some more testing to see whether I still see any falls.

However, I'd say that it's good news that you were able to run it stably
without any tuning.

Laurens
